name: CI

on:
  workflow_dispatch: 

  push:
    branches:
      - incluindo-pipeline-trabalho-conclusao-ci
  
  schedule:
    - cron: '0 2 * * *' # Executa diariamente às 02:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # instalação das dependências
      - run: npm install

      # executando testes e salvando relatório
      - run: 
          npm run test || true
          npm run report:merge

      - uses: actions/upload-artifact@v4
        with:
          path: './mochawesome-html'
