name: CI

on:
  # push:
    # branches:
    #   - incluindo-pipeline-trabalho-conclusao-ci

  schedule:
    - cron: '0 9 * * *' # Executa diariamente às 09:00 UTC

  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # instalação das dependências
      - run: npm install

      # executando testes e salvando relatório
      - run: 
          npm run test || true
          npm run report:merge

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: './mochawesome-report'
          name: relatorio-testes
